Default: Spectral
Fonts:
  - Spectral:
      Primary: "Spectral/Spectral-Light.ttf"
      Italic: "Spectral/Spectral-LightItalic.ttf"
      Bold: "Spectral/Spectral-Bold.ttf"
      Italic-Bold: "Spectral/Spectral-BoldItalic.ttf"